# Required
version: 2

# Image to use
build:
  os: ubuntu-20.04  # for consistency, matches the one used for CI
  tools:
    python: "3.9"

# Configuration
python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
